%\VignetteIndexEntry{Parallel line Assay: AntibioticAgarDiffusionAssay}
%\VignetteDepends{pla}
%\VignetteEngine{Sweave}
\documentclass[12pt, DIV16]{scrreprt}
\usepackage{Sweave}
\usepackage{booktabs}
\usepackage{caption}
\usepackage{chngcntr}

% \usepackage{helvet}
%\renewcommand{\familydefault}{\sfdefault}

% http://www.tug.dk/FontCatalogue/
% http://www.tug.dk/FontCatalogue/lcmss/
% Computer Modern Sans Serif Quotation
\usepackage[T1]{fontenc}
\renewcommand*\sfdefault{lcmss}
\renewcommand*\familydefault{\sfdefault} 
%% Only if the base font of the document is to be sans serif

\counterwithout{figure}{chapter}
\counterwithout{table}{chapter}
\title{Parallel Linje Analyser ved R}
\author{Jens Henrik Badsberg}
\date{14.\ juni 2015}
\begin{document}
%\maketitle

\begin{flushright}
  {\footnotesize Computer Modern Sans Serif Quotation}
\end{flushright}

\medskip

{\scriptsize
  \noindent
  5.1.2. THREE-DOSE LATIN SQUARE DESIGN \\
  Antibiotic agar diffusion assay using a rectangular tray. \\
  The standard has an assigned potency of 4855 IU/mg. The
  test preparation has an assumed potency of 5600 IU/mg.
  For the stock solutions 25.2 mg of the standard is dissolved
  in 24.5 ml of solvent and 21.4 mg of the test preparation
  is dissolved in 23.95 ml of solvent. The final solutions are
  prepared by first diluting both stock solutions to 1/20 and
  further using a dilution ratio of 1.5.

  \noindent
  A Latin square is generated with the method described
  in Section 8.6 (see Table 5.1.2.-I). The responses of this
  routine assay are shown in Table 5.1.2.-II (inhibition zones
  in mm x 10). The treatment mean values are shown in
  Table 5.1.2.-III. 
  
  \noindent
  A graphical representation of the data (see
  Figure 5.1.2.-I) gives no rise to doubt the normality or
  homogeneity of variance of the data.
}

<<eval=TRUE,echo=FALSE>>=
library(pla)
library(xtable)
source("R/xtables.R")
Agar     <- read.table("data/AntibioticAgarDiffusionAssay.txt", header = TRUE)
select   <- c("Row", "Column", "Sample", "Dilution", "Response")
PHframe  <- data2assayFrame(Agar[, select])
f <- (4855 * 25.2/24.5) / (5600 * 21.4 / 23.95)
factor <- c(5600 * f, 100 * f, NA)
names(factor) <- c("Potency", "Rel.\ to Ass.", "Rel.\ to Est.")
plaModel <- plaLSD(Agar, dilutionRatio = 1.5, factor = factor,
                   echoData = FALSE)
@ 
<<eval=TRUE,echo=FALSE>>=
Fits <- fit(plaModel)
@ 
<<echo=False, results=tex>>=
xtablesAssay(data = NULL, frame = Agar, model = plaModel, fits = Fits)
@
\setkeys{Gin}{width=1.00\textwidth}
\begin{figure}[h]
  \centering
<<echo=FALSE, eval=TRUE, fig=TRUE, width=6, height=4>>=
plots <- plot(plaModel, plots = "all", mfrow = c(3, 4))
@ 
\caption{\textit{Models and Residuals.}}
\end{figure}
\end{document}
